### ISSUE TITLE
External references from destroy provisioners are deprecated

### ISSUE THREAD

**Issue by 0x01m4rv** [qsecure-labs/overlord#5]
**Describe the bug**
The script throws the following error during deployment.

External references from destroy provisioners are deprecated
                                                                                                                                                                                               
  on ../../redbaron/modules/aws/dns-c2/main.tf line 84, in resource "null_resource" "gen_ssh_config":
  84:     command = "rm ssh_configs/config_${random_id.server[count.index].hex}"
                                                                                               
Destroy-time provisioners and their connection configurations may only                         
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.                                                                                    
                                                                                               
References to other resources during the destroy phase can cause dependency                    
cycles and interact poorly with create_before_destroy.
                                              
**Screenshots**
![image](https://user-images.githubusercontent.com/16485430/92366929-69cdf780-f113-11ea-9ccf-976cfa733239.png)

**Desktop:**
 - OS: Kali Linux
 - Version 2020

**Comment by V4K11** [comment]
Hello, this is a warning which appeared after we upgraded from Terraform 0.11 to 0.12. It does not cause any problems in the deploying or destroying phase and cannot be fixed due to Terraform 0.12 limitations.
