### ISSUE TITLE
Mail Server Setup

### ISSUE THREAD

**Issue by mkannan22** [qsecure-labs/overlord#8]
set domains -a text.xyz
set aws_access_key = xxx
set aws_secret_key = xxx
usemodule mail
set domain_name test.xyx
set provider aws
set region us-east-1
set allowed_ips x.x.x.x
usage: set [-h] {region,size,provider,domain_name,subdomain,allowed_ips} ...
set: error: unrecognized arguments: x.x.x.x

What am I missing for the allowed ips command?

I have attempted adding the IP a number of ways and different IP's. For example, x.x.x.x or x.x.x.x/32 or x.x.x.x, y.y.y.y or x.x.x.x,y.y.y.y

**Comment by Sikkis** [comment]
As it stated in the documentation the allowed IPs are used for devices to be able to send emails from different IP addresses . We do not recommend setting up msil servers on AWS as it needs several days to be whitelisted from Amazon. Please reas the documentation and our blogposts for futher details.

**Comment by mkannan22** [comment]
Thanks for the info. I've reviewed the blog post and wiki here, tested again with Digital Ocean, but still receiving 
set: error: unrecognized arguments: x.x.x.x after entering set allowed_ips x.x.x.x

Should I be entering the IP a specific way or setting something at the global level before this step? All other fields I can set without issue, such as domain_name (which I previously set with set domain -a xyz.xyz), subdomain, provider, and region. In other words I think there is a step I am missing before setting the allowed_ips since no matter what I enter there I get the same error.

**Comment by Sikkis** [comment]
Can you send us the commands you are running and the table with all the modules ?

**Comment by mkannan22** [comment]
set domains -a text.xyz
set aws_access_key = xxx
set aws_secret_key = xxx
usemodule mail
set domain_name test.xyx
set provider digitalocean (tried AWS too)
set region NYC1 (used AWS region as well)
 
+-------------+-----------------+----------+--------------------------------------------------+
|   VARIABLE  |      VALUE      | REQUIRED | DESCRITPION                                      |
+-------------+-----------------+----------+--------------------------------------------------+
|      id     |      CADOBQ     |   yes    | Module ID                                        |
| domain_name | xyz.com |   yes    | Domain Name to use                               |
|  subdomain  |       mail      |   yes    | Subdomain to use                                 |
| allowed_ips |        []       |   yes    | IPs which are allowed to connect to relay emails |
|   provider  |   digitalocean  |   yes    | Provider to be used                              |
|    region   |       NYC1      |   yes    | Regions to create Droplet in.                    |
|     size    |   s-1vcpu-1gb   |    no    | Droplet size to launch.

(Overlord : xxxxx/mail)$> set allowed_ips x.x.x.x
usage: set [-h] {region,size,provider,domain_name,subdomain,allowed_ips} ...
set: error: unrecognized arguments: x.x.x.x

**Comment by V4K11** [comment]
![image](https://user-images.githubusercontent.com/52568161/108956579-9dc4b700-7678-11eb-9744-eafc91a1b8f1.png)

You have to use -m if the allowed IP is another module (gophish) or -c if you want to add custom allowed IPs.

**Comment by mkannan22** [comment]
Got it. I was under the impression that the -m would be automatically allowing that IP (e.g. gophish). The -c flag is the key I was missing. Thanks!!!
